server.port: 9412
spring.application.name: ttc-spring-common

spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:oracle:thin:@10.36.126.152:1521:UNIDB
  username: UNIFORM_WATER
  password: UNIFORM_WATER_1234
  driver-class-name: oracle.jdbc.OracleDriver
  hikari:
    poolName: Hikari
    auto-commit: false
    cache-prep-stmts: false
    max-lifetime: 2

spring:
  redis:
    host: 10.37.11.78
    port: 6379
    password: password123
    timeout: 10000
spring.jpa:
  database-platform: org.hibernate.dialect.Oracle12cDialect
  show-sql: true
  properties:
    hibernate.id.new_generator_mappings: true
    hibernate.connection.provider_disables_autocommit: true
    hibernate.cache.use_second_level_cache: false
    hibernate.cache.use_query_cache: false
    hibernate.generate_statistics: false
    hibernate.jdbc.batch_size: 25
    hibernate.order_inserts: true
    hibernate.order_updates: true
    hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.format_sql: true
    hibernate.default_schema: UNIFORM_WATER
  hibernate:
    ddl-auto: none
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

security:
  oauth2:
    client:
      clientId: browser
      clientSecret: 1234
      accessTokenUri: https://uniform-gateway-uat.lienvietpostbank.com.vn/uaa/oauth/token
      grant-type: client_credentials
    resource:
      userInfoUri: https://uniform-gateway-uat.lienvietpostbank.com.vn/uaa/user/current

#response-code.prefix: uni01
ms-template-timeout-request: 1000
cluster:
  redis:
    host2: 10.37.11.184
    port2: 6379
    password2: password123